config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "up" => "rails/health#show", as: :rails_health_check

  resources :routines, only: [:index, :show, :create, :update, :destroy] do
    resources :messages, only: [:create]
  end
end

app/models/routine.rb
class Routine < ApplicationRecord
  acts_as_chat
  belongs_to :user
  has_many :messages, dependent: :destroy #routine.messages
  has_many :exercises, through: :routine_exercises
  has_many :routine_exercises, dependent: :destroy
  #validates :title, presence: true
  #validates :goal, presence: true
  after_initialize :set_chat
  def set_chat
    @chat = RubyLLM.chat
  end
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController

    def index
    @image = ["skipping.png", "big_curl2.png", "dumbell_pose.png", "bicep_curl.png", "sprint.png"]
    @routines = current_user.routines
    @routine = Routine.new
    end

    def create
        @routine = Routine.new(routine_params)
        @routine.user = current_user
        @routine.save!
        if @routine.save
            @message = Message.new({content: ""})
            @message.role = 'user'
            @message.routine = @routine
            if @message.valid?
              # TODO: Have the AI to answer this message
              AiInitialPromptService.new(@message).call
            end

            redirect_to routine_path(@routine)
        else
            render :new
        end
    end

    def show
      @image = ["running.gif", "squat.gif", "big_curl.gif", "big_curling.gif", "sprint.gif", "treadmill_fun.gif"]
      @routine = Routine.find(params[:id])
      @message = Message.new
      redirect_to root_path unless @routine.user = current_user
    end

    def edit
      @routine = Routine.find(params[:id])
      redirect_to root_path unless @routine.user = current_user
    end

    def update
        @routine = Routine.find(params[:id])
        if @routine.update(routine_params)
            @message = Message.new({content: ""})
            @message.role = 'user'
            @message.routine = @routine
            UpdatePromptService.new(@message).call
            redirect_to routine_path(@routine)
        else
            render :edit
        end
    end

    def destroy
      @routine = Routine.find(params[:id])
      redirect_to root_path unless routine.user = current_user
      @routine.destroy
      redirect_to routines_path
    end
end

private

def routine_params
    params.require(:routine).permit(:title, :goal, :equipment, :comments)
end

app/views/routines/index.html.erb
<div class="container">

<!-- Page Banner -->
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.7),rgba(0,0,0,0.7)), url(<%= asset_path("easy_gym.png") %>);">
  <div class="container">
    <h1>Your Routines</h1>
    <p>Explore your routines, add a new one, or get advice from the AI coach</p>

    <button class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#modalform">Create new routine</button>
    <div class="modal fade" id="modalform" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Create Routine</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <%= simple_form_for @routine, html: { data: {controller: "loading"} } do |f| %>
                    <%= f.input :title %>
                    <%= f.input :goal %>
                    <%#= f.input :experience, as: :radio_buttons, collection: [['Beginner', 'beginner'], ['Intermediate', 'intermediate'], ['Advanced', 'advanced']], item_wrapper_class: 'form-check', item_label_class: 'form-check-label' %>
                    <%= f.input :equipment %>
                    <%= f.input :comments %>
                    <%= f.button :submit, class:"btn btn-warning", data: { action: "click->loading#start", loading_target: "button"} %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
  </div>
</div>




<!-- Search Form -->
<%= simple_form_for :search, url: routines_path, method: :get do |f| %>
  <div class="search-form-control form-group mt-5 mb-5 w-25">
    <input class="form-control string required" type="text" name="search[query]" id="search_query" />
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i> Search
    </button>
  </div>
<% end %>

<!-- Routine Cards -->
<div class="container mb-5">
  <div class="row">
    <% @routines.each do |routine| %>
    <div class="col-12 col-sm-6 col-md-4">
    <%= link_to routine_path(routine) do %>
      <div class="card-trip mt-4">
        <%= image_tag @image.sample, alt: "Cardio home gym equipment." %>
        <div class="card-trip-infos">
          <div>
            <h2><%= routine.title %></h2>
            <p><%= routine.goal %></p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  <% end %>
  </div>
</div>
</div>

app/views/routines/show.html.erb
<div class="container">
  <!-- Page Banner -->
  <div class="banner mb-5" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url(<%= asset_path(@image.sample) %>);">
    <%= link_to routines_path, class: "btn btn-outline-secondary position-btn" do %>
      <i class="fa-regular fa-circle-left text-white"></i> <span class="text-white">Routines</span>
    <% end %>
    <div class="container position-banner">
      <h1 class="mb-3">Your routine</h1>
      <button class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#modalcomment1">Revise</button>
      <div class="modal fade" id="modalcomment1" tabindex="-1">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Revise your routine</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <%= simple_form_for [@routine, @message], html: { data: {controller: "loading"} } do |f| %>
                <%= f.input :content, label: "What would you like to change?" %>
                <%= f.button :submit, class:"btn btn-warning", data: { action: "click->loading#start", loading_target: "button"} do %>
                Update Plan
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div>
    <%= @routine.messages.where(role: 'assistant').order(:created_at).last&.content.html_safe %>
    <div class="align-vertical-center d-flex justify-content-center">
      <button class="btn btn-warning " data-bs-toggle="modal" data-bs-target="#modalcomment">Revise</button>
    </div>
  </div>
  <div class="modal fade" id="modalcomment" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Revise your routine</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= simple_form_for [@routine, @message], html: { data: {controller: "loading"} } do |f| %>
            <%= f.input :content, label: "What would you like to change?" %>
            <%= f.button :submit, class:"btn btn-warning", data: { action: "click->loading#start", loading_target: "button"} do %>
            Update Plan
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<!-- need to fix the code below -->
<!-- <%#= link_to "Edit", edit_routine_path(@routine), class: "btn btn-warning" %> -->
<!-- <%#= link_to "Create a new routine", new_routine_path, class: "btn btn-warning" %> -->